### ISSUE TITLE
Having 'all day' events

### ISSUE THREAD

**Issue by Kmacpher** [NovaFox161/DisCal-Discord-Bot#13]
Lovely bot, I'm enjoying it!

I would love to be able to schedule events that do not have a specific start and end time. In a Google Calendar, when in the 'week' view, they would be the events that show up at the top of the calendar, rather than taking up 'busy' time within the day itself. 

I think these would be great for designating birthdays, deadlines, when people are out, etc. 

Thanks!

**Comment by Kmacpher** [comment]
Thanks for the prompt response! 

I was digging into the Java Google docs a bit, and it seems an event will automatically be an all day event if the EventDateTime is set in the format  "yyyy-mm-dd" without the time. I'm unsure about this, but that is my understanding from reading the docs and perhaps that info will help.

<img width="758" alt="screen shot 2017-10-03 at 7 59 29 am" src="https://user-images.githubusercontent.com/9064637/31124146-23395e66-a811-11e7-958b-b0d792f361c1.png">

Either way, thanks for your hard work, and I'll check out the discord and Trello board in the future.

**Comment by NovaFox161** [comment]
Yeah, we are working on trying to get that to work. The Google Calendar API is pretty crap so its extremely hard to actually get it to work.

**Comment by NovaFox161** [comment]
Technically this was added in forever ago. Due to google's API being dumb as hell, its not as clean as a solution, the only way to do it is to manually specify the start/end times to be 24 hours.
