### ISSUE TITLE
Rsvp

### ISSUE THREAD

**Issue by givemhell** [NovaFox161/DisCal-Discord-Bot#14]
ive tried to google around for an answer but i cant seem to find anything

i tryed to use the rsvp command and 

Givemhell - !rsvp
DisCalBOT - You must specify a function to execute! Use '!help` for a full list of valid commands and functions!

i am prob missing a prefix or suffix but i cant find any example or info on the rsvp command

**Comment by givemhell** [comment]
well in case anyone else has my problem you can type 

!help rsvp

Example
!rsvp <subCommand> <eventId>
Sub-Commands = not, onTime, late, unsure, list, remove
<> = required | () = optional

**Comment by xaanit** [comment]
You can type `!help <command>` for any of our commands to get more info about it.
