### ISSUE TITLE
Messaging @everyone?

### ISSUE THREAD

**Issue by adaeoran** [NovaFox161/DisCal-Discord-Bot#15]
Unless I missed a specific command, I can't figure out how to make DisCal send a message to @everyone.

I set up a series of multiple test events on his calendar using the !event create command (and the following commands), but when the event time comes up, he doesn't make announcements.

Am I doing something wrong?

**Comment by xaanit** [comment]
You need to create announcements manually, using the announcement creator (or making Lazy Discal do it for you). From those announcements you can subscribe the literal string `everyone`
