### ISSUE TITLE
Time shift on events

### ISSUE THREAD

**Issue by NovaFox161** [NovaFox161/DisCal-Discord-Bot#6]
When creating events, times are displayed correctly, however once confirmed the time is shifted.

Replication:
Create a calendar with a timezone that is not US Central time.
Create an event.
Confirm said event.
View and the time will be off.

So far this has only been confirmed with calendars in the America/Los_Angeles timezone.

If you have this issue, please comment on this issue, rate, or provide us feedback. We need to confirm how widespread this bug is.

**Comment by NovaFox161** [comment]
Lily has reported that with timezone "America/New_York" it shifts by 1 hour.

**Comment by StephanMa** [comment]
I can confirm this for timezone "Europe/Berlin".

Original starting time: 8PM
Converted time: 3 AM

Maybe related to #3

**Comment by basvroegop** [comment]
I've had the same with Europe/Amsterdam. 

Original starting time 7PM, converted time 3AM. Both the same difference and same timezone as @StephanMa reported (both Amsterdam and Berlin are CET).

**Comment by NovaFox161** [comment]
Hopefully fixed in the most recent commit https://github.com/NovaFox161/DisCal-Discord-Bot/commit/44a42ae5ae5de7e86ecd9296e1dfa13e3bd1d18b

Still needs testing...

**Comment by NovaFox161** [comment]
Officially fixed in commit: https://github.com/NovaFox161/DisCal-Discord-Bot/commit/c934d128d864aaf84cde9212a4a1aabd1e062206
