### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by basvroegop** [NovaFox161/DisCal-Discord-Bot#7]
It would be great being able to make an event recur daily, weekly or monthly. Though I'm guessing this won't be viable until we can edit events.

**Comment by NovaFox161** [comment]
Will be added to TODO list and should appear in the coming updates...

**Comment by NovaFox161** [comment]
Work on this enhancement has been started in commit: https://github.com/NovaFox161/DisCal-Discord-Bot/commit/ff005a453b5cd76609fec519ca355611559dd28b
